name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          rustup default nightly
          cargo build --verbose

      - name: Test
        run: cargo test --tests --verbose -- --test-threads=1
